### ISSUE TITLE
Vue 如何实现 jwt

### ISSUE THREAD

**Issue by ahKevinXy** [dylan921208/blog#15]

**Comment by diveDylan** [comment]
前端不需要任何逻辑上的处理，依然根据`header[token]`流程实现请求流程，`jwt`由后端实现
参考博客：
[jwt 实践以及与 session 对比](https://juejin.im/post/5b532492e51d455d6825c0cc)

**Comment by ahKevinXy** [comment]
你用过jwt吗

**Comment by ahKevinXy** [comment]
> 前端不需要任何逻辑上的处理，依然根据`header[token]`流程实现请求流程，`jwt`由后端实现
> 参考博客：
> [jwt 实践以及与 session 对比](https://juejin.im/post/5b532492e51d455d6825c0cc)

现在理解透了,感觉不需要前端如何操作,只需要,后端给token,如何判断后端的状态
