### ISSUE TITLE
Vue 中如何操作导航栏的内容

### ISSUE THREAD

**Issue by ahKevinXy** [dylan921208/blog#26]
detail :

  layout 里面 有个foot 元素
我想在new.vue 的组件内操作layout组件内的foot组件是否展示,
现在不知道怎么操作啊

**Comment by ahKevinXy** [comment]
我想通过路由去判断,好像获取不到router 信息

**Comment by diveDylan** [comment]
请上代码

**Comment by diveDylan** [comment]
$route


> 我想通过路由去判断,好像获取不到router 信息

this.$route

**Comment by ahKevinXy** [comment]
> $route
> 
> > 我想通过路由去判断,好像获取不到router 信息
> 
> this.$route

获取不到路由 route 对象

**Comment by ahKevinXy** [comment]
已经找到解决方案了
