### ISSUE TITLE
vue created 请求接口,接口时间太长导致,dom渲染完成,数据还没有加载出来,导致页面上报参数 undefined 

### ISSUE THREAD

**Issue by ahKevinXy** [dylan921208/blog#29]
网上有这样的解决方案 https://blog.csdn.net/CuiCui_web/article/details/97920926

感觉不是很好,有什么好的建议,我的想法是延迟dom渲染等 接口返回再去渲染,网上好像没有找到

**Comment by diveDylan** [comment]
骨架屏，loading，dom先渲染在加载数据才是王道 @ahKevinXy

**Comment by ahKevinXy** [comment]
不太懂骨架
